# Required environment variables:
# APP_MEDIA_PATH - directory path
# APP_CACHE_PATH - directory path
# APP_DATA_PATH - directory path
# APP_DATA_URL - internal file:// path
services:
  deno:
    container_name: sauropod
    image: denoland/deno:2.4.1
    command: deno run --no-lock --unstable-cron --allow-all /app/mod.ts --dev --cron --sync
    restart: unless-stopped
    environment:
      APP_MEDIA_PATH: /mnt/media
      APP_CACHE_PATH: /mnt/cache
      APP_DATA_PATH: /mnt/data
      APP_DATA_URL: ${APP_DATA_URL}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
    volumes:
      - ${APP_MEDIA_PATH}:/mnt/media:ro
      - ${APP_CACHE_PATH}:/mnt/cache
      - ${APP_DATA_PATH}:/mnt/data
      - ./components:/app/components:ro
      - ./routes:/app/routes:ro
      - ./src:/app/src:ro
      - ./static:/app/static:ro
      - ./app.html:/app/app.html:ro
      - ./deno.jsonc:/app/deno.jsonc:ro
      - ./mod.ts:/app/mod.ts:ro
