# Required environment variables:
# DENO_KV_ACCESS_TOKEN - random string
# APP_MEDIA_PATH - directory path
# APP_CACHE_PATH - directory path
# APP_DATA_PATH - directory path

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  denokv:
    container_name: sauropod_denokv
    image: ghcr.io/denoland/denokv:0.7.0
    command: --sqlite-path /data/denokv.sqlite serve --access-token ${DENO_KV_ACCESS_TOKEN}
    restart: unless-stopped
    environment:
      DENO_KV_ACCESS_TOKEN: ${DENO_KV_ACCESS_TOKEN}
    volumes:
      - ${APP_DATA_PATH}:/data
    networks:
      - backend

  deno:
    container_name: sauropod_deno
    image: denoland/deno:1.45.5
    command: deno run --no-lock --unstable-kv --unstable-cron --allow-all /app/mod.ts --dev --cron --sync
    restart: unless-stopped
    depends_on:
      - denokv
    environment:
      DENO_KV_URL: http://denokv:4512
      DENO_KV_ACCESS_TOKEN: ${DENO_KV_ACCESS_TOKEN}
      APP_MEDIA_PATH: /mnt/media
      APP_CACHE_PATH: /mnt/cache
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
    volumes:
      - ${APP_MEDIA_PATH}:/mnt/media:ro
      - ${APP_CACHE_PATH}:/mnt/cache
      - ./components:/app/components:ro
      - ./routes:/app/routes:ro
      - ./src:/app/src:ro
      - ./static:/app/static:ro
      - ./app.html:/app/app.html:ro
      - ./deno.json:/app/deno.json:ro
      - ./mod.ts:/app/mod.ts:ro
    networks:
      - frontend
      - backend
